[pytest]
# Включает подробный вывод результатов (verbose)
addopts = -s -v


# Указывает папку, где хранятся ваши тесты
testpaths = tests

#Указываем маски для поиска тестовых файлов
python_files = test_*.py *_test.py

# Регистрация кастомного маркера
markers =
    smoke: быстрые проверки базовой функциональности