[pytest]
# Включает подробный вывод результатов (verbose)
addopts = -s -v -q


# Указывает папку, где хранятся ваши тесты
testpaths = tests

#Указываем маски для поиска тестовых файлов
python_files = test_*.py *_test.py



# pytest.ini

markers =
    ui: UI tests with Playwright
    api: API tests
    slow: Slow tests (run separately)
# Регистрация кастомного маркера
    smoke: быстрые проверки базовой функциональности



